### ISSUE TITLE
Steam profile set to public, plugin says its private; achievements and library not syncing

### ISSUE THREAD

**Issue by vulchor** [FriendsOfGalaxy/galaxy-integration-steam#133] opened 2021-09-19 14:04 UTC
Note: I have not used Galaxy in a few months, so I don't know when this problem would have started.

A couple days ago I noticed that none of the Steam achievements I've unlocked on Steam in the past month or so had synced in Galaxy. The playtime was correct. I disconnected and reconnected my Steam account using the integration in an attempt to fix the issue. I was met with a message box I've never seen before after I input my credentials. It said that my Steam profile was set to private. I knew this was not the case but doubled checked anyway, all my profile privacy settings are set to public. The retry button kept returning the same message. End up clicking Skip, but still my achievements would not sync.

After repeating this multiple times, restarting Galaxy after each reconnect and not getting the achievements to sync, today I decided to delete the plugin from %localappdata%\GOG.com\Galaxy\plugins\installed\ so Galaxy would redownload it. Now not only do I still get the "Your profile isn't set to public" prompt, but none of my Steam library will sync.

**Comment by vulchor** [comment] 2021-09-19 14:11
As luck would have it, right after I wrote this bug report I did a third restart of Galaxy after I had redownloaded the plugin, and thankfully now my Steam library has synced. I'm leaving the bug report open because I still have the problem with the plugin saying my profile is set to public and my achievements from August and September still have not synced.

**Comment by FriendsOfGalaxy** [comment] 2021-09-20 07:42
Hello, thanks for the issue.

Please attach logs so I know exactly what happen in the code (instruction here: https://github.com/FriendsOfGalaxy/galaxy-integration-steam/wiki/Log-files).

Not synced achievements is a separate problem and should not be related to private profile.

If you have public steam profile I would suggest to use fully profile-based solution, check how: 
https://github.com/FriendsOfGalaxy/galaxy-integration-steam#configuration-of-the-backend-operation-mode

Let me know if it helps.

**Comment by vulchor** [comment] 2021-09-21 06:54
I cleared all my logs since I had almost a gigabyte of them. I then disconnected the steam plugin, waited for the changes to take effect, and restarted Galaxy.

I reconnected the steam plugin and logged into my account, waited about 7 minutes. My Steam library still hadn't imported, so I restarted Galaxy.

Upon relaunch of Galaxy, it started importing my library. Once that was done, I checked the status of some of my steam games I have achievements in, and none of them had been imported, even with games that Galaxy used to show unlocked. After waiting for another 7 minutes, I closed Galaxy.

Here are the relevant logs.  I haven't tried switching the plugin over to only profile-based as I again got that error message saying my Steam profile isn't public. Let me know if you think I should still do so anyway.

Thanks
[galaxy logs.zip](https://github.com/FriendsOfGalaxy/galaxy-integration-steam/files/7200896/galaxy.logs.zip)
.

**Comment by FriendsOfGalaxy** [comment] 2021-09-23 13:46
This: "Steam profile set to public, plugin says its private" should be fixed in version 1.0.1 released just now.

About achievements:
- from your logs looks like Galaxy didn't even start asking for achievements before the restart. Probably some GOG internal error while importing library, so achievements weren't fetched as well.
- after restart it imported achievements in a standard way about 2 seconds after games were returned, you can check the steam plugin log for lines like that:
``` 2021-09-21 01:41:26,566 - galaxy.api.jsonrpc - INFO - Sending notification: method=game_achievements_import_success, params={'game_id': '50300', 'unlocked_achievements': [Achievement(unlock_time=1509853138, ```

so it imported achievements for inter alia this game: https://steamdb.info/app/50300/ . Which games didn't have an achievements at the time you've checked? It is important to know if the plugin returns wrong data or the Galaxy is not showing unlocked achievements despite returned from plugin

I was already reported that the plugin returns empty list of unlocked achievements erroneously: #117 
(but I coulnd't reproduce this).

If you could check that - It would be awesome.
You can also try a import data directly from your public steamcommunity profile by editing config at `%LocalAppData%\GOG.com\Galaxy\plugins\installed\steam_plugin_config.ini`

**Comment by Azekthi** [comment] 2021-09-23 23:36
I'm having the same issue. I had deleted and reinstalled Galaxy because #74 was never-ending, so all of the data was empty. I installed the new version of the plugin and did not change the configuration. It did not grab achievements for most of my games (example, Sea of Thieves). However, I closed Galaxy, changed the config to use my public profile instead, and re-opened Galaxy, and voila, all of my achievements have been synced.

Here's the relevant log files: [logs.zip](https://github.com/FriendsOfGalaxy/galaxy-integration-steam/files/7221273/logs.zip)

**Comment by FriendsOfGalaxy** [comment] 2021-09-24 06:03
Ok, I can see that plugin returns no achievements for Sea of Thieves, so definitely a plugin fault. Not sure if a bug or Steam protocols logic has changed but it is my next priority to fix achievements for `steam_network` backend. Then improve situation with frequent connection lost for `steam_network` (1.1).

I'm closing this task as the first problem was fixed and the second one was already reported here: #117 
Subscribe to that issue  to stay synced with achievements problem.

**Closed by FriendsOfGalaxy** 2021-09-24 06:03 UTC
