### ISSUE TITLE
new plugin can't auto connect steam after restart gog

### ISSUE THREAD

**Issue by wserious** [FriendsOfGalaxy/galaxy-integration-steam#39] opened 2020-03-06 07:27 UTC
I'm in China.
Thanks for the new released plugin, but I've got a issue. The new plugin worked fine when I connect steam acount for the first time, but if I shut down gog then restart it, the plugin can't auto reconnect the steam account. It shows 'offline' and nothing happened after clicking 'retry' or just waiting for 10 minutes. If I click 'disconnect' and then click 'connect' steam account, it worked again.
Then I checked the log file. It shows the following things. The log file is uploaded as txt. In the file, I restart gog at 2020-03-06 15:13:22. Hope It will help you.

_2020-03-06 15:13:29,244 - protocol.protobuf_client - INFO - Session id: 111947262
2020-03-06 15:13:29,244 - protocol.protocol_client - WARNING - Received unknown error, code: 5
2020-03-06 15:13:29,244 - protocol.websocket_client - ERROR - Failed to establish authenticated WebSocket connection InvalidCredentials()
Traceback (most recent call last):
  File "C:\Users\94843\AppData\Local\GOG.com\Galaxy\plugins\installed\steam\protocol\websocket_client.py", line 69, in run
    await auth_task
  File "C:\Users\94843\AppData\Local\GOG.com\Galaxy\plugins\installed\steam\protocol\websocket_client.py", line 187, in _authenticate
    ret_code = await self._protocol_client.authenticate_token(self._user_info_cache.steam_id, self._user_info_cache.account_username, self._user_info_cache.token, auth_lost_handler)
  File "C:\Users\94843\AppData\Local\GOG.com\Galaxy\plugins\installed\steam\protocol\protocol_client.py", line 174, in authenticate_token
    raise translate_error(result)
galaxy.api.errors.InvalidCredentials
2020-03-06 15:13:29,245 - galaxy.task_manager - ERROR - Task manager plugin external: exception raised in task 2 (Run WebSocketClient)
Traceback (most recent call last):
  File "C:\Users\94843\AppData\Local\GOG.com\Galaxy\plugins\installed\steam\galaxy\task_manager.py", line 21, in task_wrapper
    result = await coro
  File "C:\Users\94843\AppData\Local\GOG.com\Galaxy\plugins\installed\steam\protocol\websocket_client.py", line 69, in run
    await auth_task
  File "C:\Users\94843\AppData\Local\GOG.com\Galaxy\plugins\installed\steam\protocol\websocket_client.py", line 187, in _authenticate
    ret_code = await self._protocol_client.authenticate_token(self._user_info_cache.steam_id, self._user_info_cache.account_username, self._user_info_cache.token, auth_lost_handler)
  File "C:\Users\94843\AppData\Local\GOG.com\Galaxy\plugins\installed\steam\protocol\protocol_client.py", line 174, in authenticate_token
    raise translate_error(result)
galaxy.api.errors.InvalidCredentials
2020-03-06 15:13:33,283 - galaxy.api.jsonrpc - DEBUG - Received 54 bytes of data
2020-03-06 15:13:33,283 - galaxy.api.jsonrpc - INFO - Handling request: id=5, method=ping, params={}
2020-03-06 15:13:33,283 - root - DEBUG - Sending data: {"jsonrpc": "2.0", "id": "5", "result": null}
2020-03-06 15:13:38,349 - galaxy.api.jsonrpc - DEBUG - Received 54 bytes of data
2020-03-06 15:13:38,349 - galaxy.api.jsonrpc - INFO - Handling request: id=6, method=ping, params={}
2020-03-06 15:13:38,349 - root - DEBUG - Sending data: {"jsonrpc": "2.0", "id": "6", "result": null}_

[plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.txt](https://github.com/FriendsOfGalaxy/galaxy-integration-steam/files/4297045/plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.txt)

**Comment by wserious** [comment] 2020-03-06 07:31
Forget to say. I have steam mobile safe guard. Does it have any impact?

**Comment by FriendsOfGalaxy** [comment] 2020-03-06 09:46
Hello,

i have a guess what could be the cause of this, some of the information for refreshing credentials is stored in utf-8 encoding which might not be enough for some more advanced character sets.

Thank you for the report, i will work on it sometime soon!

**Comment by rautobias** [comment] 2020-04-12 00:45
I get the same crash after restarting GOG Galaxy client: ```Failed to establish authenticated WebSocket connection InvalidCredentials()```
There are a lot of special characters included in my password: ```():{}^'?```. But all of them should be part of UTF-8 encoding.

**Comment by FriendsOfGalaxy** [comment] 2020-04-14 12:32
Hi @rautobias 
As the plugin has changed since OP, please attach your logs. See how: https://github.com/FriendsOfGalaxy/galaxy-integration-steam/wiki/Log-files

**Comment by rautobias** [comment] 2020-04-14 18:49
The logs are attached. The problem exists since version 0.47 (new authentication flow).

[plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log](https://github.com/FriendsOfGalaxy/galaxy-integration-steam/files/4477120/plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log)

**Comment by FriendsOfGalaxy** [comment] 2020-04-15 14:55
Thanks! I was investigating this issue and have a semi-solution ready in an upcoming update. It seem that sometimes when authenticating with the stored token we receive an unexpected error message from steam backend, right now we would translate that to a plugin crash but instead we will put the plugin in offline mode since the stored token is probably ok.

This will result in the plugin still being operable and displaying all the games etc. and also ready to try connecting again when the user clicks on 'retry' button.

This is the best solution i could come up with right now but will definitely revisit the issue at some point in time.

**Comment by rautobias** [comment] 2020-04-23 15:19
I've tried the new version. The plugin now goes into offline state as expected. Then the installed games are no longer displayed in the GOG Galaxy Client. I'm not sure if this is the expected behaviour.

I will attach the new logs (including after clicking "Retry"). Hopefully the underlying problem can be fixed in the future.

[plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log](https://github.com/FriendsOfGalaxy/galaxy-integration-steam/files/4523413/plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log)

**Comment by FriendsOfGalaxy** [comment] 2020-04-27 06:54
Regarding installed games, it seems that Galaxy Client doesn't even ask for them in this situation, which is an issue on Client side since local state of the games shouldn't have anything to do with authentication.

**Comment by Hackebein** [comment] 2020-12-28 11:58
It's still a bug in version 0.53
I'm using Steam Guard. 
I removed all special characters from my password for testing but it makes no difference.

[plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log](https://github.com/FriendsOfGalaxy/galaxy-integration-steam/files/5747156/plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log)

**Comment by Hackebein** [comment] 2020-12-28 12:03
Just found out that this can be closed, because it's the same like https://github.com/FriendsOfGalaxy/galaxy-integration-steam/issues/74

**Comment by FriendsOfGalaxy** [comment] 2021-01-19 12:36
Yes, lets keep one issue for this problem

**Closed by FriendsOfGalaxy** 2021-01-19 12:36 UTC
