### ISSUE TITLE
100% achievements reset

### ISSUE THREAD

**Issue by lionnesquaer** [FriendsOfGalaxy/galaxy-integration-steam#70] opened 2020-06-20 23:56 UTC
Ok, try to explain.

4 years ago i open 100% achievements in Steam using 3rd party softaware Steam Achivements Manager, just for fun, and change my mind and reset all achivements. 
So i setup GOG login to Steam plugin, and i see that 100% achievements open 4 years ago, but the game on current moment have 0% achivements.
But, its very annoyning that i have 100% achievements for now, it was joke in the past and now i cant play the game and open achievements fair.  I like to play fair, doesnt matter result.
Is any way to make GOG see current achivements on Steam or reset they?

**Comment by rautobias** [comment] 2020-06-21 11:37
Duplicate of #35

**Comment by FriendsOfGalaxy** [comment] 2020-06-22 07:46
@lionnesquaer  thanks for the report, i didnt know such tools existed, i will look into it. 
Right now we receive the information from steam servers that an achievement was unlocked, i will need to check if there is additional information about whether it was revoked at some point or is no longer active.

**Comment by lionnesquaer** [comment] 2020-06-22 13:21
@FriendsOfGalaxy  Hope it is possible to fix!

**Comment by FriendsOfGalaxy** [comment] 2020-07-03 10:26
Closing as duplicate #35 , keep watching this thread

**Closed by FriendsOfGalaxy** 2020-07-03 10:26 UTC
