### ISSUE TITLE
Random Games Not Displaying Until Toggling Subscription Detection

### ISSUE THREAD

**Issue by SkyNinja** [FriendsOfGalaxy/galaxy-integration-steam#62] opened 2020-05-12 01:41 UTC
**Describe the bug**
After first connecting Steam, all games seem to import correctly until the process is completed, at which point the "Owned Games" number abruptly went from over 1000 to around 350. Filtering to Steam games only shows that only a couple hundred are displayed, and no filter changes seem to display the rest. After toggling subscription detection, all games reappeared in my owned games list.

**To Reproduce**
1. Disconnect Steam if already connected
2. Initiate a fresh connection to Steam
3. Allow all games to import

**Expected behavior**
All detected games are displayed as owned immediately.

**Log file**
This issue was detected in tandem with #61, so the log contained there should contain information relevant to this issue as well.

**Comment by FriendsOfGalaxy** [comment] 2020-05-12 13:26
Hi @SkyNinja , 

please provide an example of a game which is not displayed.

**Comment by SkyNinja** [comment] 2020-05-12 19:06
Ah, right. I noticed that Agony and Agony Unrated were both not displayed.

**Comment by FriendsOfGalaxy** [comment] 2020-05-13 07:15
From what i can see plugin sends both Agony and Agony Unrated as part of owned games, it doesn't even send those games as part of family sharing so the issue is even weirder.

Imho Galaxy is having trouble handling your big library of games and it takes a long time for it to display the correct data, but that is mostly a guess since i don't really know what is going on there.  

Your best bet is creating a ticket at mantis2.gog.com so Galaxy people can see it. 

Hope you get around to resolving it!

**Closed by FriendsOfGalaxy** 2020-05-13 07:15 UTC
