### ISSUE TITLE
Disconnect from Steam every day or few

### ISSUE THREAD

**Issue by SylwesterZarebski** [FriendsOfGalaxy/galaxy-integration-steam#27] opened 2019-12-22 17:23 UTC
**Describe the bug**
Steam disconnect every day/few days of inactivity.

**To Reproduce**
Open Galaxy 2.0 on day 1 and connect to Steam account.
Do not use Galaxy 2 one day or more - use Steam client normally.
Open Galaxy 2.0 client - client shows connection lost to Steam.

**Expected behavior**
Do not disconnect from Steam.

**Attached logs**
Relevant log part after Galaxy 2.0 start:
```
2019-12-22 18:05:16,285 - root - DEBUG - Using proactor: IocpProactor
2019-12-22 18:05:16,286 - galaxy.api.plugin - INFO - Using local address: 127.0.0.1:13779
2019-12-22 18:05:16,286 - galaxy.api.plugin - INFO - Creating plugin for platform steam, version 0.41.2
2019-12-22 18:05:16,327 - galaxy.api.jsonrpc - DEBUG - Received 66 bytes of data
2019-12-22 18:05:16,327 - galaxy.api.jsonrpc - INFO - Handling request: id=0, method=get_capabilities, params={}
2019-12-22 18:05:16,327 - root - DEBUG - Sending data: {"jsonrpc": "2.0", "id": "0", "result": {"platform_name": "steam", "features": ["InstallGame", "ImportFriends", "ImportGameTime", "ImportInstalledGames", "UninstallGame", "ImportGameLibrarySettings", "ShutdownPlatformClient", "LaunchGame", "ImportOwnedGames", "ImportUserPresence", "ImportAchievements"], "token": "9f0e5603-c36f-415c-ae5d-fa701e55787d"}}
2019-12-22 18:05:16,511 - galaxy.api.jsonrpc - DEBUG - Received 155685 bytes of data
2019-12-22 18:05:16,513 - galaxy.api.jsonrpc - INFO - Handling request: id=1, method=initialize_cache, params={'data': '****'}
2019-12-22 18:05:16,516 - galaxy.task_manager - DEBUG - Task manager plugin internal: creating task 0 (tick)
2019-12-22 18:05:16,516 - root - DEBUG - Sending data: {"jsonrpc": "2.0", "id": "1", "result": null}
2019-12-22 18:05:16,516 - galaxy.task_manager - DEBUG - Task manager plugin external: creating task 0 (Update owned games)
2019-12-22 18:05:16,517 - galaxy.task_manager - DEBUG - Task manager plugin external: finished task 0 (Update owned games)
2019-12-22 18:05:16,612 - galaxy.api.jsonrpc - DEBUG - Received 54 bytes of data
2019-12-22 18:05:16,612 - galaxy.api.jsonrpc - INFO - Handling request: id=2, method=ping, params={}
2019-12-22 18:05:16,612 - root - DEBUG - Sending data: {"jsonrpc": "2.0", "id": "2", "result": null}
2019-12-22 18:05:16,843 - galaxy.api.jsonrpc - DEBUG - Received 1758 bytes of data
2019-12-22 18:05:16,843 - galaxy.api.jsonrpc - INFO - Handling request: id=3, method=init_authentication, params={'stored_credentials': '****'}
2019-12-22 18:05:16,843 - galaxy.task_manager - DEBUG - Task manager jsonrpc server: creating task 0 (init_authentication)
2019-12-22 18:05:16,843 - galaxy.task_manager - DEBUG - Task manager plugin external: creating task 1 (init_authentication)
2019-12-22 18:05:16,844 - galaxy.api.jsonrpc - INFO - Sending notification: method=store_credentials, params={'cookies': '****'}
2019-12-22 18:05:16,844 - galaxy.api.jsonrpc - DEBUG - Sending 1834 bytes of data
2019-12-22 18:05:17,195 - galaxy.api.jsonrpc - INFO - Sending notification: method=store_credentials, params={'cookies': '****'}
2019-12-22 18:05:17,195 - galaxy.api.jsonrpc - DEBUG - Sending 1683 bytes of data
2019-12-22 18:05:17,233 - backend - ERROR - Can not parse backend response - no a.user_avatar
2019-12-22 18:05:17,234 - root - DEBUG - Sending data: {"jsonrpc": "2.0", "id": "3", "error": {"code": 100, "message": "Invalid credentials"}}
2019-12-22 18:05:17,234 - galaxy.task_manager - DEBUG - Task manager jsonrpc server: finished task 0 (init_authentication)
```

I can confirm i do not have any avatar set on Steam if i correctly read error.

**Comment by SylwesterZarebski** [comment] 2019-12-22 17:44
Log after client restart, this time no disconnect:
```
2019-12-22 18:40:46,378 - root - DEBUG - Using proactor: IocpProactor
2019-12-22 18:40:46,380 - galaxy.api.plugin - INFO - Using local address: 127.0.0.1:2627
2019-12-22 18:40:46,380 - galaxy.api.plugin - INFO - Creating plugin for platform steam, version 0.41.2
2019-12-22 18:40:46,414 - galaxy.api.jsonrpc - DEBUG - Received 66 bytes of data
2019-12-22 18:40:46,415 - galaxy.api.jsonrpc - INFO - Handling request: id=0, method=get_capabilities, params={}
2019-12-22 18:40:46,415 - root - DEBUG - Sending data: {"jsonrpc": "2.0", "id": "0", "result": {"platform_name": "steam", "features": ["ImportAchievements", "InstallGame", "ImportFriends", "ImportUserPresence", "LaunchGame", "ImportInstalledGames", "ImportGameLibrarySettings", "UninstallGame", "ShutdownPlatformClient", "ImportOwnedGames", "ImportGameTime"], "token": "84407955-f90b-4da2-b29a-09182b55e850"}}
2019-12-22 18:40:46,627 - galaxy.api.jsonrpc - DEBUG - Received 155686 bytes of data
2019-12-22 18:40:46,630 - galaxy.api.jsonrpc - INFO - Handling request: id=1, method=initialize_cache, params={'data': '****'}
2019-12-22 18:40:46,633 - galaxy.task_manager - DEBUG - Task manager plugin internal: creating task 0 (tick)
2019-12-22 18:40:46,633 - root - DEBUG - Sending data: {"jsonrpc": "2.0", "id": "1", "result": null}
2019-12-22 18:40:46,634 - galaxy.task_manager - DEBUG - Task manager plugin external: creating task 0 (Update owned games)
2019-12-22 18:40:46,634 - galaxy.task_manager - DEBUG - Task manager plugin external: finished task 0 (Update owned games)
2019-12-22 18:40:46,729 - galaxy.api.jsonrpc - DEBUG - Received 54 bytes of data
2019-12-22 18:40:46,729 - galaxy.api.jsonrpc - INFO - Handling request: id=2, method=ping, params={}
2019-12-22 18:40:46,729 - root - DEBUG - Sending data: {"jsonrpc": "2.0", "id": "2", "result": null}
2019-12-22 18:40:46,957 - galaxy.api.jsonrpc - DEBUG - Received 1759 bytes of data
2019-12-22 18:40:46,957 - galaxy.api.jsonrpc - INFO - Handling request: id=3, method=init_authentication, params={'stored_credentials': '****'}
2019-12-22 18:40:46,957 - galaxy.task_manager - DEBUG - Task manager jsonrpc server: creating task 0 (init_authentication)
2019-12-22 18:40:46,957 - galaxy.task_manager - DEBUG - Task manager plugin external: creating task 1 (init_authentication)
2019-12-22 18:40:46,958 - galaxy.api.jsonrpc - INFO - Sending notification: method=store_credentials, params={'cookies': '****'}
2019-12-22 18:40:46,958 - galaxy.api.jsonrpc - DEBUG - Sending 1835 bytes of data
2019-12-22 18:40:47,635 - galaxy.task_manager - DEBUG - Task manager plugin external: creating task 2 (Update owned games)
2019-12-22 18:40:47,635 - galaxy.task_manager - DEBUG - Task manager plugin external: finished task 2 (Update owned games)
2019-12-22 18:40:47,915 - galaxy.task_manager - DEBUG - Task manager plugin external: creating task 3 (Run WebSocketClient)
2019-12-22 18:40:47,915 - root - DEBUG - Remember login cookie not present
2019-12-22 18:40:47,915 - galaxy.task_manager - DEBUG - Task manager plugin external: finished task 1 (init_authentication)
2019-12-22 18:40:47,915 - servers_cache - DEBUG - servers_cache entry was not found in cache
2019-12-22 18:40:47,916 - root - DEBUG - Sending data: {"jsonrpc": "2.0", "id": "3", "result": {"user_id": "76561198048718150", "user_name": "SylwesterZ"}}
```

**Comment by SylwesterZarebski** [comment] 2019-12-23 20:51
PS. I have dynamic IP which change every day (sometimes more often).

**Comment by FriendsOfGalaxy** [comment] 2019-12-27 12:06
Hey,

can you confirm that you have 'Remember me on this computer' selected when logging in to plugin?
![image](https://user-images.githubusercontent.com/48480506/71516458-66f2e580-28a9-11ea-90ed-1c7ee6223dbe.png)

**Comment by SylwesterZarebski** [comment] 2019-12-27 12:42
Yes, i confirm. This field is automatically set when above window is opened.

**Comment by SylwesterZarebski** [comment] 2020-01-01 11:23
I've checked for few days if starting Steam before GOG helps, but it didn't help.

**Comment by FriendsOfGalaxy** [comment] 2020-01-03 15:38
> PS. I have dynamic IP which change every day (sometimes more often).

that may be the case... 
We base on cookies returned from login window.  ` ERROR - Can not parse backend response - no a.user_avatar` means you not logged in anymore - cookies are invalidated by steam, most commonly due to long period passed from last session activity OR for any other reason Steam unvalidate a cookie. You can check if the same is happening on webbrowser. If so, we cannot help with current login implementation.

**Comment by SylwesterZarebski** [comment] 2020-01-03 16:06
I'll check it out. Logged now, restarted router, refresh steam page and i've been logged out :-(

**Comment by FriendsOfGalaxy** [comment] 2020-01-10 15:07
So its caused by design (cookie invalidation by Steam for different IP). For any future references, this cannot be fixed in current login implementation

Won't be problem if we change login method to SteamClient-native, or to API keys #2

**Closed by FriendsOfGalaxy** 2020-01-10 15:07 UTC

**Comment by SylwesterZarebski** [comment] 2020-01-11 12:51
Thanks, i understand and will wait for change login method.
