### ISSUE TITLE
Plugin consistently crashing on new installation

### ISSUE THREAD

**Issue by EP01** [FriendsOfGalaxy/galaxy-integration-steam#77] opened 2020-07-18 19:42 UTC
**Description**
Brand new installation. Trying GOG Galaxy for the first time. Steam integration plugin consistently crashes during import, after around 2-10 minutes each time. If I close Galaxy and reopen, it might add a few games before crashing (though most don't "stick", i.e. they're gone the next time the client is loaded). I have a large Steam library (6000+ games) so that may be a factor.

I've tried a few clean re-installs, including manually deleting leftover files after un-installation. I've tried an install with only the Steam plugin chosen. No difference to the behaviour.

I'm a software dev with some experience in Python, so I'm willing to aid in debugging and/or creating a PR if needed, however I'd need some time to become familiar with the project. 

Please let me know if I can provide any more information.

**Attached logs**
I've attached the logs from the past few hours of testing.
[logs.zip](https://github.com/FriendsOfGalaxy/galaxy-integration-steam/files/4942367/logs.zip)

**Comment by FriendsOfGalaxy** [comment] 2020-08-17 15:24
Hello @EP01, I'm sorry for late response.

It looks like there is blocking code in asyncio loop. After a few seconds with no response on ping method, Galaxy kills plugin as unresponsive. 

GalaxyClient.log:
```
2020-07-18 20:25:34.554 [Error][ (0)] [TID 8764][galaxy_client]: Plugin - pluginID/steam_ca27391f-2675-49b1-92c0-896d43afa4f8 is not responding.
(...)
2020-07-18 20:25:35.686 [Warning][ (0)] [TID 8764][galaxy_client]: Plugin pluginID/steam_ca27391f-2675-49b1-92c0-896d43afa4f8 shutdown failed, killing process
2020-07-18 20:25:35.686 [Error][ (0)] [TID 8764][galaxy_client]: Plugin - pluginID/steam_ca27391f-2675-49b1-92c0-896d43afa4f8 has crashed.
```

Plugin log is cut off after logging `Skipping already resolved packages`. You have many licences so there must be something in the code that blocks asyncio loop for too long. We have to put it in separate thread. (`ProtocolClient._license_import_handler`) I've prepared version with more logs and when fill cache in separate thread, please test it out:
[possible fix for parsing licences.zip](https://github.com/FriendsOfGalaxy/galaxy-integration-steam/files/5085149/possible.fix.for.parsing.licences.zip)

Test by reconnecting plugin first, to have a clear cache.
Close Galaxy after each files change.

**Comment by dandepeched** [comment] 2020-08-18 12:11
@FriendsOfGalaxy , I tried this build, but crash still occurs. I cleaned up all previous steam cache and restarted Galaxy app before plugin installation.
In logs I see some exceptions, but not before the crash. Crash is still observed in a random place.
Logs are attached.
[logs.zip](https://github.com/FriendsOfGalaxy/galaxy-integration-steam/files/5090269/logs.zip)

**Comment by dandepeched** [comment] 2020-08-18 12:47
I tried to sync second time after crash with 'Retry' and it worked this time. Sync was performed for ~20 minutes, but than it continues infinitely with the following message returning after each re-sync - "Licenses list different than last time".
Logs are attached
[logs.zip](https://github.com/FriendsOfGalaxy/galaxy-integration-steam/files/5090420/logs.zip)

**Comment by FriendsOfGalaxy** [comment] 2020-08-19 07:19
@dandepeched thanks for logs. Can you also send `GalaxyClient.log`? It is much easier to spot when exactly Galaxy thinks plugin is unresponsive

**Comment by dandepeched** [comment] 2020-08-19 07:33
@FriendsOfGalaxy , sure, here they are:
[logs.zip](https://github.com/FriendsOfGalaxy/galaxy-integration-steam/files/5094694/logs.zip)

**Comment by FriendsOfGalaxy** [comment] 2020-08-19 08:36
Hmm, interesting. The only crash event that can be seen in both Galaxy and plugin log is:

```2020-08-18 15:07:19.151 [Error][ (0)] [TID 20728][galaxy_client]: Plugin - pluginID/steam_ca27391f-2675-49b1-92c0-896d43afa4f8 is not responding.
```
but steam plugin logs ends at 15:07:18

Looks like a different issue than OP, because plugin just stopped logging. Memory problem? @dandepeched could you monitor memory usage by the plugin? You have ~40k games, right? 

--

"Licenses list different than last time" - looks like steam is sending licenses in packs of 121994 items. That shouldn't be problem, we're updating cache every time, just this log is a missleading in that case.

**Comment by FriendsOfGalaxy** [comment] 2020-08-19 08:47
@EP01 your input is still welcome

**Comment by EP01** [comment] 2020-08-19 09:25
Hi @FriendsOfGalaxy, thanks very much for looking into this, sorry for the delay in responding! I'm on my Mac just now, would you be able to provide a Mac build to test? If not, I'll be back on my Windows PC in about 8 hours or so, so will be able to provide some feedback then.

**Comment by FriendsOfGalaxy** [comment] 2020-08-19 09:52
Here you are:
[steam build mac.zip](https://github.com/FriendsOfGalaxy/galaxy-integration-steam/files/5095491/steam.build.mac.zip)

**Comment by EP01** [comment] 2020-08-19 11:51
@FriendsOfGalaxy 
I ran some testing on that build and threading off the task seems to have resolved the original issue. However I did encounter the same thing as @dandepeched where the first time it ran it crashed, but after clicking "retry" it succeeded and there were no more issues (attached logs from just after crash, before retrying). Also of note (though unrelated to the current issue) is that I ran into #81 when switching between my PC and Mac.

I'll continue to use this build for now until the fix is officially released. Thanks again!

[first_run_logs_crash.zip](https://github.com/FriendsOfGalaxy/galaxy-integration-steam/files/5096150/first_run_logs_crash.zip)

**Comment by EP01** [comment] 2020-08-19 12:41
@FriendsOfGalaxy 
Just got another crash after restarting Galaxy, see attached logs.

[crash_after_restarting.zip](https://github.com/FriendsOfGalaxy/galaxy-integration-steam/files/5096410/crash_after_restarting.zip)

**Comment by FriendsOfGalaxy** [comment] 2020-08-20 08:46
@EP01 

Thanks for testing!

Plugin is treated as "not responding" when it does not answer to `ping` message within some time. Reading logs more carefully it looks like the time is more than 15 seconds. In normal condition ping is send every 5 seconds. Now see strange timing in the logs:

GalaxyClient.log:
```
2020-08-19 11:58:23.233 [Error][ (0)] [TID 0x700010bc8000][galaxy_client]: Plugin - pluginID/steam_ca27391f-2675-49b1-92c0-896d43afa4f8 is not responding.
```
plugin log:
```
2020-08-19 11:58:12,328 - galaxy.api.jsonrpc - INFO - Handling request: id=31, method=ping, params={}
2020-08-19 11:58:12,328 - root - DEBUG - Sending data: {"jsonrpc": "2.0", "id": "31", "result": null}
(...)
2020-08-19 11:58:12,330 - galaxy.api.jsonrpc - INFO - Handling request: id=32, method=ping, params={}
2020-08-19 11:58:12,330 - root - DEBUG - Sending data: {"jsonrpc": "2.0", "id": "32", "result": null}
(...)
2020-08-19 11:58:13,001 - galaxy.api.jsonrpc - INFO - Handling request: id=33, method=ping, params={}
2020-08-19 11:58:13,001 - root - DEBUG - Sending data: {"jsonrpc": "2.0", "id": "33", "result": null}
(...)
2020-08-19 11:58:30,654 - galaxy.api.jsonrpc - INFO - Handling request: id=34, method=ping, params={}
2020-08-19 11:58:30,654 - root - DEBUG - Sending data: {"jsonrpc": "2.0", "id": "34", "result": null}
```

Those log lines are from:
- https://github.com/gogcom/galaxy-integrations-python-api/blob/master/src/galaxy/api/jsonrpc.py#L352
- https://github.com/gogcom/galaxy-integrations-python-api/blob/master/src/galaxy/api/jsonrpc.py#L309

Looks like 3 pings were handled quickly and 4. has been handled after long time. Maybe those 3 first were delayed because socket buffer were saturated by sending too much information from plugin to Galaxy (many `owned_games` in case of first_run_logs_crash.zip) (assuming sending and receiving data can block each other, I don't know). 

And the last ping - looks like in both crashes it was send after something like that:
```
2020-08-19 11:57:55,241 - galaxy.api.jsonrpc - INFO - Sending notification: method=owned_game_added, params={'owned_game': Game(game_id='1078000', game_title='Gamecraft', dlcs=[], license_info=LicenseInfo(license_type=<LicenseType.SinglePurchase: 'SinglePurchase'>, owner=None))}
2020-08-19 11:57:55,241 - galaxy.api.jsonrpc - DEBUG - Sending 190 bytes of data
2020-08-19 11:57:58,672 - galaxy.api.jsonrpc - INFO - Sending notification: method=push_cache, params={'data': '****'}
2020-08-19 11:57:58,692 - galaxy.api.jsonrpc - DEBUG - Sending 4344044 bytes of data
2020-08-19 11:57:58,694 - galaxy.api.jsonrpc - INFO - Sending notification: method=owned_game_added, params={'owned_game': Game(game_id='1073860', game_title='Idle Guardians', dlcs=[], license_info=LicenseInfo(license_type=<LicenseType.SinglePurchase: 'SinglePurchase'>, owner=None))}
2020-08-19 11:57:58,694 - galaxy.api.jsonrpc - DEBUG - Sending 195 bytes of data
2020-08-19 11:58:02,090 - galaxy.api.jsonrpc - INFO - Sending notification: method=push_cache, params={'data': '****'}
2020-08-19 11:58:02,109 - galaxy.api.jsonrpc - DEBUG - Sending 4344044 bytes of data
2020-08-19 11:58:02,112 - galaxy.api.jsonrpc - INFO - Sending notification: method=owned_game_added, params={'owned_game': Game(game_id='1073060', game_title='Lonely Skies', dlcs=[], license_info=LicenseInfo(license_type=<LicenseType.SinglePurchase: 'SinglePurchase'>, owner=None))}
2020-08-19 11:58:02,112 - galaxy.api.jsonrpc - DEBUG - Sending 193 bytes of data
2020-08-19 11:58:05,501 - galaxy.api.jsonrpc - INFO - Sending notification: method=push_cache, params={'data': '****'}
2020-08-19 11:58:05,520 - galaxy.api.jsonrpc - DEBUG - Sending 4344044 bytes of data
2020-08-19 11:58:05,522 - galaxy.api.jsonrpc - INFO - Sending notification: method=owned_game_added, params={'owned_game': Game(game_id='1072390', game_title='BirdGut', dlcs=[], license_info=LicenseInfo(license_type=<LicenseType.SinglePurchase: 'SinglePurchase'>, owner=None))}
2020-08-19 11:58:05,522 - galaxy.api.jsonrpc - DEBUG - Sending 188 bytes of data
2020-08-19 11:58:08,916 - galaxy.api.jsonrpc - INFO - Sending notification: method=push_cache, params={'data': '****'}
2020-08-19 11:58:08,935 - galaxy.api.jsonrpc - DEBUG - Sending 4344044 bytes of data
2020-08-19 11:58:08,938 - galaxy.api.jsonrpc - INFO - Sending notification: method=owned_game_added, params={'owned_game': Game(game_id='1067110', game_title='Idle Chess Story', dlcs=[], license_info=LicenseInfo(license_type=<LicenseType.SinglePurchase: 'SinglePurchase'>, owner=None))}
2020-08-19 11:58:08,938 - galaxy.api.jsonrpc - DEBUG - Sending 197 bytes of data
2020-08-19 11:58:12,305 - galaxy.api.jsonrpc - INFO - Sending notification: method=push_cache, params={'data': '****'}
2020-08-19 11:58:12,324 - galaxy.api.jsonrpc - DEBUG - Sending 4344044 bytes of data
(...)
```
`push_cache` send 4344044 bytes (<4MB) to Galaxy multiple times. Probably the same data that is surplus. 

----

I see the same in logs from OP. The solution with separate thread is to fix a few second delay in licenses parsing, but real problem is in plugin but pushing ~16MB cache unnecessarily that probably blocks socket from receiving ping messages.

----

A few ideas to fix this:
- do not push cache when not needed
- optimize cache data 
- optimize push_cache mechanism on Galaxy side
- push to plugin database directly omitting Galaxy (devil one)
- anything else?

**Comment by EP01** [comment] 2020-08-20 13:11
@FriendsOfGalaxy 
Please ignore me if I'm talking rubbish :D, I haven't had a chance to look at the code yet.
 
Would it be possible to separate the Ping endpoint and have it run in it's own instance and thread? That way it would always be available to respond immediately regardless of the state of the rest of the processing. Failing that, perhaps some sort of prioritization system where the other tasks can check if the Ping endpoint has been hit at certain intervals (a background timer?) and pause their execution until it's complete?

**Comment by FriendsOfGalaxy** [comment] 2020-08-20 15:07
@EP01 yes, those are valid ideas for Galaxy :)
All that communication stuff is local, so just replace "endpoint" with "another local host port". That would complicate overall system though. 
Prioritization system would is also good idea, but I'm afraid all "blocking" stuff is low level that we cannot inspect _which_ message is coming before we receive that message.

I will focus on the plugin optimization, but if you want to experiment with the Galaxy Python API to make socket communication more efficient this would be profitable for everyone.

**Comment by FriendsOfGalaxy** [comment] 2020-08-24 08:50
@EP01 could you test this build please?
[steam cace opt windows.zip](https://github.com/FriendsOfGalaxy/galaxy-integration-steam/files/5116725/steam.cace.opt.windows.zip)
[steam cache opt macos.zip](https://github.com/FriendsOfGalaxy/galaxy-integration-steam/files/5116738/steam.cache.opt.macos.zip)

(just pushing cache optimization without previous fix)

**Comment by EP01** [comment] 2020-08-24 15:57
Hey @FriendsOfGalaxy I tried the Mac build but couldn't run it because one of the external libraries (`multidict`) isn't signed, so it triggers Gatekeeper. Will give the Windows build a go when I get a chance.

**Comment by FriendsOfGalaxy** [comment] 2020-08-28 08:31
@EP01 as far as I know you can add exception for Gatekeeper. Or just test windows version

Current RC version of the plugin:
mac: [steam_4_fixes_mac.zip](https://github.com/FriendsOfGalaxy/galaxy-integration-steam/files/5140946/steam_4_fixes_mac.zip)
win: [steam_4_fixes_windows.zip](https://github.com/FriendsOfGalaxy/galaxy-integration-steam/files/5140952/steam_4_fixes_windows.zip)

To install it:
0 close Galaxy Client
1 delete the contents of your C:\Users\Username\AppData\Local\GOG.com\Galaxy\plugins\installed\steam_ca27391f-2675-49b1-92c0-896d43afa4f8 folder
2 unpack the contents of windows.zip folder to C:\Users\Username\AppData\Local\GOG.com\Galaxy\plugins\installed\steam_ca27391f-2675-49b1-92c0-896d43afa4f8 folder
3 run Galaxy Client

**Comment by EP01** [comment] 2020-08-28 11:49
@FriendsOfGalaxy 
Yeah you can manually add exceptions for Gatekeeper, it's just very tedious and time-consuming to do every binary as there's no batch method (other than turning the whole thing off).

However, I did it for the build you sent today and can confirm that the crash on launch is now gone. Thanks very much!

I would have tested on my Windows machine, but I've now got a weird issue with that, where since I've had a successful Steam sync on my Mac, the Windows client will just crash on launch; and I'm talking about the whole Galaxy client, not the plugin. Probably something dodgy cached there so will try a cache clear/reinstall there at some point.

**Comment by sgreadly** [comment] 2020-11-18 19:28
I've been directed here by GOG Support. Can I confirm if my issue is related?

I noticed GOG Galaxy 2.0.23 (3) on my Catalina 10.15.7 is leaking memory for Python daemon. It would be around ~700MB mark. A day later it clims up to 1.13GB, and counting.. It's a slow leak - around ~100kb every ~15 seconds

I'm not doing anything at all (not playing games etc.. it was weekend and I was away so it was just sitting idle).

[Screen Shot 2020-10-19 at 11.17.34 AM.png](https://support.gog.com/attachments/token/xIP4W3x99DaY0dWalLgjhgcDi/?name=Screen+Shot+2020-10-19+at+11.17.34+AM.png)
[Screen Shot 2020-10-19 at 11.17.39 AM.png](https://support.gog.com/attachments/token/qQTzwBJaS4nr6EQAGiaMqPMaS/?name=Screen+Shot+2020-10-19+at+11.17.39+AM.png)
[open_files_and_ports.txt](https://support.gog.com/attachments/token/O3xtIngOdgzl5sNe6Qkm6ajLm/?name=open_files_and_ports.txt)
[sample_text.txt](https://support.gog.com/attachments/token/ptKoizGoHgOuViaC9lQ21mRHV/?name=sample_text.txt)
[Log files](https://support.gog.com/attachments/token/44eJQpl54Nj9m0V0tJakPeKuM/?name=Logs.zip)

**Comment by sgreadly** [comment] 2020-11-30 23:14
If it helps with the above comment, this is still reproducible on Big Sur 11.0.1, with a successful connection to Steam via GOG plugin - back then I had a connectivity problem where I had to reinstall the plugin, and I suspected this may have been causing the leak..

**Comment by FriendsOfGalaxy** [comment] 2020-12-25 14:24
@sgreadly looks like it is unrelated. Thanks for submitting separate report.

**Comment by FriendsOfGalaxy** [comment] 2021-01-11 09:49
@EP01 a new version was released some time ago, so I assume we can close this issue. I'm happy to have it done - previous cache management was so clunky.

**Closed by FriendsOfGalaxy** 2021-01-11 09:49 UTC
