### ISSUE TITLE
Frequent crashes after a while ("Task was destroyed but it is pending!"/CancelledErrors)

### ISSUE THREAD

**Issue by BuryTomorrow12** [FriendsOfGalaxy/galaxy-integration-steam#3] opened 2019-08-07 01:02 UTC
Greetings.

Steam integration keeps sending a message stating "Plugin has crashed. Retry". No matter the retries, happens over and over.

Tried unlinking and relinking Steam account, same issue. Relauching Galaxy 2.0 won't help.

If there's a specific file you need, let me know.

**Comment by BuryTomorrow12** [comment] 2019-08-08 01:47
Today I tried uninstalling latest release of this integration (deleting all the files), redownloading latest release and installing it. The issue still happens.
![steam](https://user-images.githubusercontent.com/40051760/62669236-46aba400-b965-11e9-9a7c-808547f95a32.PNG)

**Comment by pivotiiii** [comment] 2019-08-08 19:30
Same problem on my client, however I never even got to the actual login.

**Comment by Danyelalejandro** [comment] 2019-08-13 22:56
Same problem with me. "Plugin has crashed. Retry" is permanent. 
This could be related to the ammount of Steam games maybe? I have almost 2000

**Comment by FriendsOfGalaxy** [comment] 2019-08-14 08:19
@BuryTomorrow12 @pivotiiii @Danyelalejandro 
Could you please share your c:\ProgramData\GOG.com\Galaxy\logs\plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log?

**Comment by pivotiiii** [comment] 2019-08-14 13:43
This is a fresh file after a reboot and ran as admin.
[plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8 (1).log](https://github.com/FriendsOfGalaxy/galaxy-integration-steam/files/3501622/plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.1.log)

**Comment by BuryTomorrow12** [comment] 2019-08-16 02:42
Here's a logfile as well. Please note this is the .log.1 renamed to .log, as the .log is in use in my current session.
Also, after the latest release, it happens less often. I've only seen it happen once since the latest version of the plugin came out, while it was happening every few minutes on previous release.
[plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log](https://github.com/FriendsOfGalaxy/galaxy-integration-steam/files/3507870/plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log)

**Comment by Danyelalejandro** [comment] 2019-08-16 03:06
Guys, since I updated with the last release of this plugin (0.30) the errors has stopped apparently and the bug dissapeared. It if happens again I will upload the log.

**Comment by Danyelalejandro** [comment] 2019-08-16 23:30
Error has started for me again. Attach you will find my log

[plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log](https://github.com/FriendsOfGalaxy/galaxy-integration-steam/files/3511397/plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log)

**Comment by BuryTomorrow12** [comment] 2019-09-01 22:11
Since the last update, happens less often. However, it still happens.

Here's 2 logs, One that was renamoed automatically to .log1 when I clicked on "retry", and the new one .log

[steam integration logs.zip](https://github.com/FriendsOfGalaxy/galaxy-integration-steam/files/3563961/steam.integration.logs.zip)

There's a different issue that I'd like to state: some games do not show up on my games list in gog. Such is the example of 3DSenVR, a VR emulator on steam. Bought it yesterday, stilll doesn't show up on GoG. Curiously enough, bought a couple games after that (including another VR title) and they all show up on GoG.

Please let me know if I should open a ticket for this second issue. Thanks!

**Comment by FriendsOfGalaxy** [comment] 2019-09-02 06:57
A fix is comming for the related crashes. Should be awailable in a couple of days.
@BuryTomorrow12 missing games is 99% by GOG's side. You should report them with GLX cogwheel menu, Report Issue

**Comment by CKrawczyk** [comment] 2019-10-05 12:54
This just started happening to me today with the latest version of the plugin (0.32).  Here are my log files:
[plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log](https://github.com/FriendsOfGalaxy/galaxy-integration-steam/files/3693238/plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log)

[plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.2.log](https://github.com/FriendsOfGalaxy/galaxy-integration-steam/files/3693240/plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.2.log)

**Comment by Danyelalejandro** [comment] 2019-10-05 17:24
Hello guys, Issue came back with last update. Please help

[plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log](https://github.com/FriendsOfGalaxy/galaxy-integration-steam/files/3693535/plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log)

**Comment by christopherjtaylor** [comment] 2019-10-06 21:53
Wanted to add that this is happening to me as well with 0.32.

**Comment by CKrawczyk** [comment] 2019-10-07 08:50
Update: After restarting my computer the issue has gone away.  Not really sure why that helped.

**Comment by Danyelalejandro** [comment] 2019-10-07 22:14
In my case it still is crashing permanently

**Comment by christopherjtaylor** [comment] 2019-10-08 02:29
Same here. I've restarted, uninstalled/reinstalled the plugin, closed and re-opened the client. Crashes after just a few minutes every time.

**Comment by BlacRyu** [comment] 2019-10-08 04:15
Same problem starting happening for me today. Would post my logs but the Steam log stopped updating before the crashes started (along with origin). I tried restarting Galaxy and all of the other logs updated, except for those two. The size of the origin log is 4,999,982 bytes and the steam one is 5,000,000 so I guess there's some size limit to them. Tried renaming the log to get it to start working again and it said they were in use by Python (even after closing Galaxy). 

![image](https://user-images.githubusercontent.com/10762433/66366712-381e4080-e946-11e9-8d7b-f5f67d204207.png)

Killed the processes and started Galaxy again, hopefully everything works now.

**Comment by BlacRyu** [comment] 2019-10-10 06:46
It's been more stable for me since I killed the process. The plugin still 'crashed' once since then with the same issue (python process was hanging and log was full / old). Killed the python processes again and it's been working fine so far since. Perhaps the problem occurs when it's trying to rename the logs when they get full? The steam process is by far logging the most, with it constantly writing and filling up a log file every 6-7 minutes for me. Lots of opportunities for it to fail due to some semi-rare race condition or something.

**Comment by christopherjtaylor** [comment] 2019-10-11 05:31
I hope this isn't a terribly ignorant comment, but just wanted to 

> It's been more stable for me since I killed the process. The plugin still 'crashed' once since then with the same issue (python process was hanging and log was full / old). Killed the python processes again and it's been working fine so far since. Perhaps the problem occurs when it's trying to rename the logs when they get full? The steam process is by far logging the most, with it constantly writing and filling up a log file every 6-7 minutes for me. Lots of opportunities for it to fail due to some semi-rare race condition or something.

I hope this isn't a terribly ignorant comment, but I can definitely confirm it has something to do with the Python processes. I closed GoG, killed all 8ish Python instances that were active in my system, and then reopened GoG. Previously the plugin would crash about 30 seconds after reconnecting, but I haven't had a crash in the last 30 minutes.

**Comment by FriendsOfGalaxy** [comment] 2019-11-16 14:08
Guys, thanks for giving feedback. We need to differentiate and group issues. The generic symptoms "Plugin has crashed. Retry" can appear for whatever reason.

@christopherjtaylor @BlacRyu thanks for all the info. Looks like plugin process survived closing the Galaxy. That shoudn't happend. If you find your repro, please report issue to Galaxy and paste mantis link here for reference. I have suspicious that this may be a problem with plugin update.

@Danyelalejandro we'll investigate your case in separate issue: 
@pivotiiii it is also your case. Plus additional permission deny error. Please create separate issue with you case pasting log below, ok?

```
2019-08-11 02:39:37,773 - root - ERROR - Failed to get local games list
Traceback (most recent call last):
  File "C:\Users\pivotii\AppData\Local\GOG.com\Galaxy\plugins\installed\steam_ca27391f-2675-49b1-92c0-896d43afa4f8\local_games.py", line 109, in local_games_list
    for app_id in apps_ids:
  File "C:\Users\pivotii\AppData\Local\GOG.com\Galaxy\plugins\installed\steam_ca27391f-2675-49b1-92c0-896d43afa4f8\local_games.py", line 189, in get_installed_games
    app_id = get_app_id(app_manifest_path)
  File "C:\Users\pivotii\AppData\Local\GOG.com\Galaxy\plugins\installed\steam_ca27391f-2675-49b1-92c0-896d43afa4f8\local_games.py", line 196, in get_app_id
    config = load_vdf(app_manifest_path)
  File "C:\Users\pivotii\AppData\Local\GOG.com\Galaxy\plugins\installed\steam_ca27391f-2675-49b1-92c0-896d43afa4f8\local_games.py", line 21, in load_vdf
    return vdf.load(open(path, encoding="utf-8", errors="replace"), mapper=CaseInsensitiveDict)
  File "C:\Users\pivotii\AppData\Local\GOG.com\Galaxy\plugins\installed\steam_ca27391f-2675-49b1-92c0-896d43afa4f8\vdf\__init__.py", line 186, in load
    return parse(fp, **kwargs)
  File "C:\Users\pivotii\AppData\Local\GOG.com\Galaxy\plugins\installed\steam_ca27391f-2675-49b1-92c0-896d43afa4f8\vdf\__init__.py", line 89, in parse
    for idx, line in enumerate(fp):
PermissionError: [Errno 13] Permission denied
2019-08-11 02:39:37,820 - root - DEBUG - Received 66 bytes of data
2019-08-11 02:39:37,820 - root - INFO - Handling request: id=0, method=get_capabilities, params={}
2019-08-11 02:39:37,820 - root - DEBUG - Sending data: {"jsonrpc": "2.0", "id": "0", "result": {"platform_name": "steam", "features": ["ImportOwnedGames", "ImportAchievements", "ImportInstalledGames", "LaunchGame", "InstallGame", "UninstallGame", "ImportFriends", "ImportGameTime"], "token": "607762a6-e613-4d69-956e-0982404ac03a"}}
2019-08-11 02:39:37,821 - root - ERROR - Task exception was never retrieved
future: <Task finished coro=<StreamWriter.drain() done, defined at D:\obj\Windows-Release\37win32_Release\msi_python\zip_win32\streams.py:328> exception=ConnectionResetError('Connection lost')>
Traceback (most recent call last):
  File "D:\obj\Windows-Release\37win32_Release\msi_python\zip_win32\streams.py", line 348, in drain
  File "D:\obj\Windows-Release\37win32_Release\msi_python\zip_win32\streams.py", line 202, in _drain_helper
ConnectionResetError: Connection lost
```


---
Keep investigation for OP:
@BuryTomorrow12 thanks for your logs. Multiple errors "Task was destroyed but it is pending" are there. Probably connected with importing achievements for large library like yours. 

As you figured out logs are rolling (renaming during the time). So please follow those steps:
- Exit Galaxy
- remove all your steam logs (every number)
- launch Galaxy. Copy your fist steam log somewhere (this ending with `.log`)
- wait until first crash
- zip all your steam logs and upload here. If you have 10 log files (Galaxy limit, attach also "first log" copy you made)

This way we will have the whole information about what is happening and figure out where is the real problem. Thanks!

**Comment by BuryTomorrow12** [comment] 2019-11-16 16:42
Thank you FOG for your efforts!

Upgraded to latest version of the plugin, Happened right at launch. Here are the logs:

[steam plugin logs.zip](https://github.com/FriendsOfGalaxy/galaxy-integration-steam/files/3854426/steam.plugin.logs.zip)

**Comment by Danyelalejandro** [comment] 2019-11-16 19:55
[plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log.zip](https://github.com/FriendsOfGalaxy/galaxy-integration-steam/files/3854627/plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log.zip)
All logs zipped

**Comment by BuryTomorrow12** [comment] 2019-11-19 23:40
Since Euporia update for Galaxy 2.0, this happens every minute. Plugin crashes every 60/120 seconds.

**Comment by Danyelalejandro** [comment] 2019-11-20 01:43
I have the same problem as @BuryTomorrow12 The crashes increased in frequency. It got worse.
[plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log.zip](https://github.com/FriendsOfGalaxy/galaxy-integration-steam/files/3866877/plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log.zip)

**Comment by FriendsOfGalaxy** [comment] 2019-11-25 11:39
Looks like plugin has too many thing to send to Galaxy and rpc communication is getting overload. Then some ping messages are delayed long time and thus Galaxy kills the plugin cancelling all current coroutines.
I've passe this bug report and possible solution too GOG team. We have to wait for now.

**Comment by BuryTomorrow12** [comment] 2019-11-25 12:18
Thank you, FoG. I'd like to add that this happens every single time I launch Galaxy 2.0. If I click retry then, or during the first minutes of launching Galaxy, it **always** crashes, no matter how many times I retry.

But, If I leave galaxy open and retry after 20 minutes of having launched the program, the plugin doesn't crash anymore.

This seems to relate with what you've found out, as I blindly guess that an overload may set some kind of "deny every request this client for X minutes" policy. I don't know if it works this way, but it seems to fit.

Once again, thanks for your help on the matter, I do understand that I have a large pool of games, achievements, etc. I'll wait for the news from GoG side.

**Comment by dandepeched** [comment] 2019-11-26 06:53
Hi @BuryTomorrow12 ! Plugin is also constantly crashing for me. I'm not sure if it is the same root cause. In log I see:
`2019-11-26 08:49:11,306 - root - ERROR - Unexpected exception raised in import_game_achievements`
Log file - 
[plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log](https://github.com/FriendsOfGalaxy/galaxy-integration-steam/files/3890421/plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log)

Let me know if you need more logs.

**Comment by BanCrash** [comment] 2019-11-26 15:28
I have the same issue as @dandepeched , with "Unexpected exception raised in import_game_achievements". in the log.

**Comment by Danyelalejandro** [comment] 2019-11-26 22:31
Hello @FriendsOfGalaxy 
Problem persists. It is a nightmare. I will attach my logs as well. I hope it can be useful
[plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log.zip](https://github.com/FriendsOfGalaxy/galaxy-integration-steam/files/3894279/plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log.zip)

**Comment by FriendsOfGalaxy** [comment] 2019-12-04 09:30
Hi, latest release should fix this problem. Can you recheck now?

**Comment by dandepeched** [comment] 2019-12-04 10:52
I do not observe crashes anymore. Thanks!

**Comment by skanx** [comment] 2019-12-06 20:50
Hello, I do not have any more crashes, thank you!

**Comment by Danyelalejandro** [comment] 2019-12-06 23:39
guys, crashes stopped, thank you

**Comment by BuryTomorrow12** [comment] 2019-12-07 00:42
> Hi, latest release should fix this problem. Can you recheck now?

Tested 0.37 and 0.38.2 - So far, the issue seems to be gone. If it happens again, I'll let you know. You can safely close the issue.

Thank you for your help and dedication!

PS, a small request. Is there a chance to get a changelog with each release? Thanks!

**Comment by FriendsOfGalaxy** [comment] 2019-12-09 13:34
Thanks for confirmation guys. Closing.

> PS, a small request. Is there a chance to get a changelog with each release? Thanks!
It would be a good thing. I will check how can I add it to plugins CI

**Closed by FriendsOfGalaxy** 2019-12-09 13:34 UTC
Labels: galaxy

**Comment by Danyelalejandro** [comment] 2019-12-17 02:09
Guys, sorry to re-open but nightmare has started again
[plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log.zip](https://github.com/FriendsOfGalaxy/galaxy-integration-steam/files/3971095/plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log.zip)

**Comment by FriendsOfGalaxy** [comment] 2019-12-17 14:22
@dandepeched  looks like different issue - no errors in your logs - just silently unresponsive... please create separate task and attach also GalaxyClient.log just after such crush

**Comment by Danyelalejandro** [comment] 2019-12-18 01:19
I'll do. Thank you
